window.SOTAY_RUNTIME_CONFIG = {
    SERVER_API_BASE_URL: "/api",
    STRICT_SERVER_MODE: true,
    ENABLE_SERVER_CONTENT_API: true,
    ENABLE_SERVER_DIRECTORY_API: true,
    ENABLE_SERVER_AUTH_API: true,
    ENABLE_SERVER_CHATBOT_API: true,
    ENABLE_SERVER_SURVEY_API: true,
    ENABLE_SERVER_STATS_API: true,
    ENABLE_SERVER_NOTICE_API: true,
    ENABLE_SERVER_PUSH_API: true,
    SURVEY_API_URL: "",
    CHATBOT_WEB_APP_URL: "",
    STATS_WEB_APP_URL: "",
    SURVEY_WEB_APP_URL: "",
    FCM_VAPID_KEY: ""
};
