window.SOTAY_RUNTIME_CONFIG = {
    SERVER_API_BASE_URL: "http://localhost:5243/api",
    ENABLE_SERVER_CONTENT_API: true,
    ENABLE_SERVER_DIRECTORY_API: true,
    ENABLE_SERVER_AUTH_API: true,
    ENABLE_SERVER_CHATBOT_API: true,
    ENABLE_SERVER_SURVEY_API: true,
    ENABLE_SERVER_STATS_API: true,
    ENABLE_SERVER_NOTICE_API: true,
    ENABLE_SERVER_PUSH_API: true
};
